services:
  jellyfin:
    image: "\
      linuxserver/jellyfin@sha256:\
      747bc6725c5e4f1330e693b50d787e2106e52ac5b25c4174ca5f58915fc17ec8\
    "  # 10.11.5
    container_name: jellyfin
    env_file:
      - .env-files/linuxserverio.env
    ports:
      - 8096:8096
    volumes:
      - volumes/config:/config
      - volumes/movies:/data/movies
      - volumes/shows:/data/shows
    restart: on-failure

networks:
  default:
    name: ${CADDY_NETWORK}
    external: true
