services:
  git-http-backend:
    container_name: git-http-backend
    image: git-http-backend
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROOT: /var/www/git
    volumes:
      - volumes/root:/var/www/git
    restart: on-failure

networks:
  default:
    name: ${CADDY_NETWORK}
    external: true
