services:
  librespeed:
    image: "\
      linuxserver/librespeed@sha256:\
      6eb3a38fdab18af72e6c505cb98a0a239a6e38a06066fe38b2852876c5a3e1c7\
    "  # 5.4.1
    container_name: librespeed
    env_file:
      - .env-files/linuxserverio.env
    volumes:
      - .volumes/config:/config
    restart: on-failure

networks:
  default:
    name: ${SWAG_NETWORK}
    external: true
